# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
- group: variables
- name: svc-acc-01

steps:
  - script: |
      echo ${{variables.svc-acc-01}}

# variables:
# - name: one
#   value: initialValue 
# steps:
#   - script: |
#       echo ${{ variables.one }} # outputs initialValue
#       echo $(one)
#     displayName: First variable pass
#   - bash: echo '##vso[task.setvariable variable=one]secondValue'
#     displayName: Set new variable value
#   - script: |
#       echo ${{ variables.one }} # outputs initialValue
#       echo $(one) # outputs secondValue
#     displayName: Second variable pass
# variables:
# - group: variables
# - name: svc-acc-01
#   value: 'asd'
#   # value: $[variables.svc-acc-01] # uses runtime expression

# steps:
# - script: echo $(svc-acc-01)
# - script: echo $(asd)
# - script: echo $(variables)
# - script: echo $(azsu-d-kv-value-002)