# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


variables:
- group: variables
- name: svc-acc-01
  value: $[variables.svc-acc-01] # uses runtime expression

steps:
- script: echo $(svc-acc-01) # uses macro syntax
# - script: echo $(azsu-d-kv-value-002)